### ISSUE TITLE
UnknownException

### ISSUE THREAD

**Issue by Altamimi-Dev** [JoseGeorges8/sms_scheduler#1]
<img width="767" alt="Screen Shot 2020-11-26 at 9 56 39 AM" src="https://user-images.githubusercontent.com/73592113/100313399-03e46400-2fce-11eb-94e5-325c9746135a.png">

I have been trying to implement it in my app but for some reason, it keeps giving me the same error.

UnknownException (UnknownException(UNKNOWN, Component class com.example.sms_scheduler.RebootBroadcastReceiver does not exist in com.example.first_app))

any idea how to fix it?

**Comment by JoseGeorges8** [comment]
Hi thanks for taking the time on trying out the package! I'll take a look at why this is happening. What device are you using and what version of android?

**Comment by Altamimi-Dev** [comment]
> Hi thanks for taking the time on trying out the package! I'll take a look at why this is happening. What device are you using and what version of android?

I am android studio emulator (google pixel 3 XL with android 10

**Comment by shahshubh** [comment]
Did this issue get resolved @Altamimi-Dev cause i'm getting the same issue.
I am running on real device Redmi note 5 pro. 
Android version: 9
can you help @JoseGeorges8  ?

**Comment by Altamimi-Dev** [comment]
> Did this issue get resolved @Altamimi-Dev cause i'm getting the same issue.
> I am running on real device Redmi note 5 pro.
> Android version: 9
> can you help @JoseGeorges8 ?

@shahshubh Unfortunately i was not able to fix it seems the issue is compatibility with newer android versions 10+, still working on it to make it compatible with flutter 2.0 once done I will repost here.

**Comment by Ritikgarg1773** [comment]
Any updates??

**Comment by dhirenparmar** [comment]
Add below code in Android manifest
`       <receiver android:name="com.example.sms_scheduler.ReminderBroadcastReceiver"/>
       <receiver android:name="com.example.sms_scheduler.RebootBroadcastReceiver"
           android:enabled="false">
           <intent-filter>
               <action android:name="android.intent.action.BOOT_COMPLETED"/>
           </intent-filter>
       </receiver>
`

**Comment by Altamimi-Dev** [comment]
@Ritikgarg1773 there have been no update for 2 years so i think the package will not be updated .
